name: Release

on:
  workflow_dispatch: # Manually kick off
    inputs:
      version:
        description: >
          Optionally provide a version to bump to in 'major.minor.patch' format
          (e.g. 2.0.1). Otherwise, the patch version will be incremented
          automatically.
        required: false

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      new_version: ${{ steps.bump-version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Bump csproj version
        id: bump-version
        run: |
          optional_version=${{ github.event.inputs.version }}
          new_version=$(scripts/bump-csproj-version.sh throwaway-gh-action-test.csproj $optional_version)
          # Write the new version to the GitHub Actions output
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump version to ${{ steps.bump-version.outputs.new_version }}
          tagging_message: tester-v${{ steps.bump-version.outputs.new_version }}
